server.port: 7003
server.error.include-message: always

spring:
  jpa:
    hibernate:
      ddl-auto: update

  datasource:
    hikari:
      initialization-fail-timeout: 60000

spring.datasource:
  url: jdbc:mysql://localhost/review-db
  username: user
  password: pwd


logging:
  level:
    root: INFO
    com.islam: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

---
spring.profiles: docker
spring.datasource:
  url: jdbc:mysql://mysql/review-db
server.port: 8080